### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by Noahnc** [Scalr/pygohcl#18]
Hello Scalar Team

I noticed that pygohcl currently only supports Linux and MacOS.
Is there a specific why Windows is not supported?
I tried to add a Windows build to the GitHub Action myself in the [following PR](https://github.com/Noahnc/pygohcl/pull/2).
But for some reason, the build for Python 3.7 fails.

Thanks and best regards,
Noah

**Comment by recipe** [comment]
Hi Noahnc,
Sorry for the long delay. There is no specific reason why Windows packages are missing from the project. No one asked for them.  Personally, I haven’t used Windows for a long time, like many of my colleagues.

I started windows server on the cloud, downloaded the wheel from [your build artifacts here](https://github.com/Noahnc/pygohcl/actions/runs/6659036861#artifacts) and it turned out they were assembled incorrectly. Here is the output for the python 3.10 (Windows):
```PowerShell
PS C:\Users\vitaliy> pip freeze
cffi==1.16.0
colorama==0.4.6
exceptiongroup==1.2.0
iniconfig==2.0.0
packaging==23.2
pluggy==1.3.0
pycparser==2.21
pygohcl @ file:///C:/Users/vitaliy/Downloads/pygohcl-0.1.dev60%2Bga1cef5b-cp310-cp310-win_amd64.whl
pytest==7.4.3
tomli==2.0.1

PS C:\Users\vitaliy> python -V
Python 3.10.10

PS C:\Users\vitaliy> python
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygohcl
>>> out = pygohcl.loads(
...         """locals {
...             a = 0.19
...             b = 1 + 9
...             c = -0.82
...             x = -10
...             y = -x
...             z = -(1 + 4)
...         }"""
...     )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vitaliy\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\pygohcl\__init__.py", line 43, in loads
    return loadb(data.encode("utf8"))
  File "C:\Users\vitaliy\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\pygohcl\__init__.py", line 38, in loadb
    ffi.gc(ret.json, lib.free)
ffi.error: symbol 'free' not found in library 'C:\Users\vitaliy\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\pygo
hcl.cp310-win_amd64.pyd': error 0x7f
```
Did you try to build the windows wheel as described here https://github.com/Scalr/pygohcl?tab=readme-ov-file#building-locally?

**Comment by kapilt** [comment]
fwiw, I tried to build on windows (GitHub Actions) as well and ran into the same issue re `free` not found in library

**Comment by recipe** [comment]
My Windows build stuck on C stuff (`cygwin`).
```shell
$ pip wheel --no-deps --use-pep517 -w dist .
Processing c:\cygwin64\home\vitaliy\pygohcl
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pygohcl
  Building wheel for pygohcl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pygohcl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      running bdist_wheel
      running build
      running build_py
      copying pygohcl\__init__.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\_pygohcl.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\build_cffi.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\_pygohcl.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\__init__.py -> build\lib.win-amd64-cpython-38\pygohcl
      generating cffi module 'build\\lib.win-amd64-cpython-38\\pygohcl\\_pygohcl.py'
      already up-to-date
      running build_ext
      go: downloading github.com/hashicorp/hcl/v2 v2.10.1
      go: downloading github.com/zclconf/go-cty v1.9.1
      go: downloading github.com/agext/levenshtein v1.2.1
      go: downloading github.com/apparentlymart/go-textseg/v13 v13.0.0
      go: downloading github.com/mitchellh/go-wordwrap v0.0.0-20150314170334-ad45545899c7
      go: downloading golang.org/x/text v0.3.5
      go: downloading github.com/apparentlymart/go-textseg v1.0.0
      # runtime/cgo
      gcc_libinit_windows.c: In function â€˜_cgo_beginthreadâ€™:
      gcc_libinit_windows.c:143:27: error: implicit declaration of function â€˜_beginthreadâ€™; did you mean â€˜_cgo_beginthreadâ€™? [-Werror=implicit-function-declaration]
        143 |                 thandle = _beginthread(func, 0, arg);
            |                           ^~~~~~~~~~~~
            |                           _cgo_beginthread
      cc1: all warnings being treated as errors
      $ GOPATH='C:\cygwin64\tmp\tmpu876ob2x' go get -d
      $ CGO_CFLAGS='-Ic:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\include -Ic:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\Include' CGO_LDFLAGS='-Lc:\users\vitaliy\.pyenv\pyen
v-win\versions\3.8.10\libs -lpython3' GOPATH='C:\cygwin64\tmp\tmpu876ob2x' go build -buildmode=c-shared -o 'C:\cygwin64\home\vitaliy\pygohcl\build\lib.win-amd64-cpython-38\pygohcl.cp38
-win_amd64.pyd' '-ldflags=-s -w'
      Traceback (most recent call last):
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\normal\Lib\site-packages\cffi\setuptools_ext.py", line 199, in run
          base_class_2.run(self)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\normal\Lib\site-packages\setuptools_golang.py", line 167, in build_extension
          _check_call(cmd_build, cwd=pkg_path, env=env)
        File "C:\cygwin64\tmp\pip-build-env-3hiffj04\normal\Lib\site-packages\setuptools_golang.py", line 104, in _check_call
          subprocess.check_call(cmd, cwd=cwd, env=dict(os.environ, **env))
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '('go', 'build', '-buildmode=c-shared', '-o', 'C:\\cygwin64\\home\\vitaliy\\pygohcl\\build\\lib.win-amd64-cpython-38\\pygohcl.cp38-win_amd6
4.pyd', '-ldflags=-s -w')' returned non-zero exit status 1.
      [end of output]
```
And even when I remediated those warnings with commenting the `_cgo_beginthread` function in `gcc_libinit_windows.c` I got linker error:
```shell
 pip wheel --no-deps --use-pep517 -w dist .
Processing c:\cygwin64\home\vitaliy\pygohcl
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pygohcl
  Building wheel for pygohcl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pygohcl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      running bdist_wheel
      running build
      running build_py
      copying pygohcl\__init__.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\_pygohcl.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\build_cffi.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\_pygohcl.py -> build\lib.win-amd64-cpython-38\pygohcl
      copying pygohcl\__init__.py -> build\lib.win-amd64-cpython-38\pygohcl
      generating cffi module 'build\\lib.win-amd64-cpython-38\\pygohcl\\_pygohcl.py'
      already up-to-date
      running build_ext
      go: downloading github.com/hashicorp/hcl/v2 v2.10.1
      go: downloading github.com/zclconf/go-cty v1.9.1
      go: downloading github.com/agext/levenshtein v1.2.1
      go: downloading github.com/apparentlymart/go-textseg/v13 v13.0.0
      go: downloading github.com/mitchellh/go-wordwrap v0.0.0-20150314170334-ad45545899c7
      go: downloading golang.org/x/text v0.3.5
      go: downloading github.com/apparentlymart/go-textseg v1.0.0
      # github.com/Scalr/pygohcl
      C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
      /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex: No such file or directory
      /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32: No such file or directory
      collect2: error: ld returned 1 exit status

      $ GOPATH='C:\cygwin64\tmp\tmp6kx0hxcg' go get -d
      $ CGO_CFLAGS='-Ic:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\include -Ic:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\Include' CGO_LDFLAGS='-Lc:\users\vitaliy\.pyenv\pyen
v-win\versions\3.8.10\libs -lpython3' GOPATH='C:\cygwin64\tmp\tmp6kx0hxcg' go build -buildmode=c-shared -o 'C:\cygwin64\home\vitaliy\pygohcl\build\lib.win-amd64-cpython-38\pygohcl.cp38
-win_amd64.pyd' '-ldflags=-s -w'
      Traceback (most recent call last):
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\normal\Lib\site-packages\cffi\setuptools_ext.py", line 199, in run
          base_class_2.run(self)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\normal\Lib\site-packages\setuptools_golang.py", line 167, in build_extension
          _check_call(cmd_build, cwd=pkg_path, env=env)
        File "C:\cygwin64\tmp\pip-build-env-q3uflg2c\normal\Lib\site-packages\setuptools_golang.py", line 104, in _check_call
          subprocess.check_call(cmd, cwd=cwd, env=dict(os.environ, **env))
        File "c:\users\vitaliy\.pyenv\pyenv-win\versions\3.8.10\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '('go', 'build', '-buildmode=c-shared', '-o', 'C:\\cygwin64\\home\\vitaliy\\pygohcl\\build\\lib.win-amd64-cpython-38\\pygohcl.cp38-win_amd6
4.pyd', '-ldflags=-s -w')' returned non-zero exit status 1.
```

**Comment by kapilt** [comment]
on windows functions have to be explicitly exported by a dll (or a separate DEF file), the `free` function isn't explicitly exported so fails on usage, the parse function is explicitly exported so works. depend on your usage you can accept the memory leak by guarding the free on if sys.platform != 'win32'  .. its not clear to me if it was originally intended as free from libc or libgo, but apparently re libc that's not a thing in windows vs compiler specific CRT libs, 🤷  here's an old post from armin rigo on CFFI mailing list that denotes the export issue https://groups.google.com/g/python-cffi/c/djQHpdoz1bo/m/OJ1CkWlgAAAJ?pli=1
